### ISSUE TITLE
Windshaft npm warning about node and npm versions

### ISSUE THREAD

**Issue by rajanski** [strk/easycartodb#1]
npm WARN engine windshaft@0.27.2: wanted: {"node":">=0.8 <0.11","npm":">=1.2.1"} (current: {"node":"v0.8.9","npm":"1.1.63"})

**Comment by rajanski** [comment]
I am using the cartodb repos on ubuntu 12.04

**Comment by strk** [comment]
I think we need node-0.10 here. Do you want to provide a patch for the ./configure script so it checks node version and exist if it is not good enough ?
Once you're at it, it would be also good to check for rails...

**Comment by strk** [comment]
I made the configure check for node.js myself, the ruby/rails one is still useful
