### ISSUE TITLE
make breaks with compile error at /rails-app/Gemfile:9:in `evaluate':

### ISSUE THREAD

**Issue by rajanski** [strk/easycartodb#2]
make -C rails-app
make[1]: Entering directory `/home/app/easycartodb/rails-app'
bundle install
/home/app/easycartodb/rails-app/Gemfile:9:in`evaluate': compile error (SyntaxError)
/home/app/easycartodb/rails-app/Gemfile:9: syntax error, unexpected ':', expecting $end
gem 'sequel_pg',               '1.6.3', require: 'sequel'
                                                ^
    from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:17:in `build'
    from /usr/lib/ruby/vendor_ruby/bundler.rb:136:in`definition'
    from /usr/lib/ruby/vendor_ruby/bundler/cli.rb:222:in `install'
    from /usr/lib/ruby/vendor_ruby/bundler/vendor/thor/task.rb:22:in`send'
    from /usr/lib/ruby/vendor_ruby/bundler/vendor/thor/task.rb:22:in `run'
    from /usr/lib/ruby/vendor_ruby/bundler/vendor/thor/invocation.rb:118:in`invoke_task'
    from /usr/lib/ruby/vendor_ruby/bundler/vendor/thor.rb:246:in `dispatch'
    from /usr/lib/ruby/vendor_ruby/bundler/vendor/thor/base.rb:389:in`start'
    from /usr/bin/bundle:13
make[1]: **\* [all] Error 1
make[1]: Leaving directory `/home/app/easycartodb/rails-app'
make: **\* [all] Error 2

**Comment by rajanski** [comment]
ubuntu 1204, using cartodb repos

**Comment by strk** [comment]
This is best filed upstream: https://github.com/CartoDB/cartodb/
Sounds like "bundle install" would fail there too, right ?

**Comment by rajanski** [comment]
it was wrong ruby version..
works with 1.9.3 installed via rvm
close

**Comment by strk** [comment]
What version of ruby were you running before ?

**Comment by rajanski** [comment]
i think 1.8.7

**Comment by strk** [comment]
As of a51d6e96210e610ecfd01fe7ab8cb99607766ed5 ruby version should also be checked
