### ISSUE TITLE
redis running, but make check returns Redis connection to 127.0.0.1:6335 failed - connect ECONNREFUSED

### ISSUE THREAD

**Issue by rajanski** [strk/easycartodb#4]

**Comment by strk** [comment]
Redis should be supposedly started to listen on port 6335 by the map-api/run_test.sh script, which is run by "make check"  from the map-api/ dir which is invoked by "make check" in the top-dir.

Take a look at the map-api/run_test.sh script and maybe add some debugging calls there.

For debugging, you could call the script to just start redis, run a simple test and kill it like this:
`
cd map-api/
./run_tests.sh --nocreate-pg test/acceptance/cache_validator.js 
`

**Comment by rajanski** [comment]
map-api/run_tests.sh --nocreate-pg test/acceptance/cache_validator.js 
passes

**Comment by strk** [comment]
Try `make -C map-api check` again ?

**Comment by rajanski** [comment]
sorry ,i had a second instance fof redis running .. works now

**Comment by strk** [comment]
Great, keep sending more bugs, I'm ready :)

**Comment by rajanski** [comment]
ahh noo sorry Uncaught Error: Redis connection to 127.0.0.1:6336 failed - connect ECONNREFUSED

**Comment by strk** [comment]
New ticket needed for 6336, this one was for 6335 :)

**Comment by rajanski** [comment]
haha..
;-)
any way it is not working..

**Comment by strk** [comment]
Ok I see you're not willing to file another bug so let's discuss it here.
Port 6336 is the port used by the testing redis instance of sql-api, so similar suggestions than the ones I gave for the map-api case apply to the sql-api case here.

That is, `make -C sql-api check`

The "run_test.sh" script for sql-api might be a big older than the one for map-api, so you might not have the --nocreate-pg switch (hint: you could add that !).

**Comment by strk** [comment]
Closing for lack of feedback
